language: ruby
rvm:
 - "2.2.3"
# uncomment this line if your project needs to run something other than `rake`:
script: bin/rspec spec

test:
  adapter: mysql2
  database: passit_test
  username: travis
  encoding: utf8

before_script:
  - mysql -e 'create database passit_test;'